///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExitPromptText
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ExitPromptTextRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("85661981-01ec-4e83-b9c5-9d590a5a8ade")]
    public partial class ExitPromptTextRepository : RepoGenBaseFolder
    {
        static ExitPromptTextRepository instance = new ExitPromptTextRepository();
        ExitPromptTextRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        ExitPromptTextRepositoryFolders.SystemExitAppFolder _systemexit;

        /// <summary>
        /// Gets the singleton class instance representing the ExitPromptTextRepository element repository.
        /// </summary>
        [RepositoryFolder("85661981-01ec-4e83-b9c5-9d590a5a8ade")]
        public static ExitPromptTextRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ExitPromptTextRepository() 
            : base("ExitPromptTextRepository", "/", null, 0, false, "85661981-01ec-4e83-b9c5-9d590a5a8ade", ".\\RepositoryImages\\ExitPromptTextRepository85661981.rximgres")
        {
            _snapxuntitled = new ExitPromptTextRepositoryFolders.SnapXUntitledAppFolder(this);
            _systemexit = new ExitPromptTextRepositoryFolders.SystemExitAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85661981-01ec-4e83-b9c5-9d590a5a8ade")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("2929d7c5-2cd8-410d-a9aa-f8c11df543f6")]
        public virtual ExitPromptTextRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The SystemExit folder.
        /// </summary>
        [RepositoryFolder("e1a214e0-aa51-496b-bc20-190b7f0a7139")]
        public virtual ExitPromptTextRepositoryFolders.SystemExitAppFolder SystemExit
        {
            get { return _systemexit; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class ExitPromptTextRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("2929d7c5-2cd8-410d-a9aa-f8c11df543f6")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _measuretextInfo;
            RepoItemInfo _switchtosensorInfo;
            RepoItemInfo _switchtoffwInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "2929d7c5-2cd8-410d-a9aa-f8c11df543f6", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 30000, null, "c01137ed-84d1-41bb-96d4-443f114b97d5");
                _measuretextInfo = new RepoItemInfo(this, "MeasureText", "container[@controlid='59648']/form[@title='Untitled']//text[@controlid='2394']", 30000, null, "c62e34df-bc6e-4690-8ec8-0be1536ac473");
                _switchtosensorInfo = new RepoItemInfo(this, "SwitchToSensor", "container[@controlid='59648']/form[@title='Untitled']/?/?/element[@controlid='59650']/element[@controlid='59648']/toolbar[@controlid='59392']/button[@commandid='40029']", 30000, null, "6371d4e3-96ee-4b7e-8358-785c65e1cc1c");
                _switchtoffwInfo = new RepoItemInfo(this, "SwitchToFFW", "container[@controlid='59648']/form[@title='Untitled']//toolbar[@class='ToolbarWindow32' and @instance='7']/button[@commandid='40028']", 30000, null, "d9c95d65-49dc-4683-ba73-55cf3a6ab1ab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2929d7c5-2cd8-410d-a9aa-f8c11df543f6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2929d7c5-2cd8-410d-a9aa-f8c11df543f6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("c01137ed-84d1-41bb-96d4-443f114b97d5")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("c01137ed-84d1-41bb-96d4-443f114b97d5")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The MeasureText item.
            /// </summary>
            [RepositoryItem("c62e34df-bc6e-4690-8ec8-0be1536ac473")]
            public virtual Ranorex.Text MeasureText
            {
                get
                {
                    return _measuretextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MeasureText item info.
            /// </summary>
            [RepositoryItemInfo("c62e34df-bc6e-4690-8ec8-0be1536ac473")]
            public virtual RepoItemInfo MeasureTextInfo
            {
                get
                {
                    return _measuretextInfo;
                }
            }

            /// <summary>
            /// The SwitchToSensor item.
            /// </summary>
            [RepositoryItem("6371d4e3-96ee-4b7e-8358-785c65e1cc1c")]
            public virtual Ranorex.Button SwitchToSensor
            {
                get
                {
                    return _switchtosensorInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchToSensor item info.
            /// </summary>
            [RepositoryItemInfo("6371d4e3-96ee-4b7e-8358-785c65e1cc1c")]
            public virtual RepoItemInfo SwitchToSensorInfo
            {
                get
                {
                    return _switchtosensorInfo;
                }
            }

            /// <summary>
            /// The SwitchToFFW item.
            /// </summary>
            [RepositoryItem("d9c95d65-49dc-4683-ba73-55cf3a6ab1ab")]
            public virtual Ranorex.Button SwitchToFFW
            {
                get
                {
                    return _switchtoffwInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SwitchToFFW item info.
            /// </summary>
            [RepositoryItemInfo("d9c95d65-49dc-4683-ba73-55cf3a6ab1ab")]
            public virtual RepoItemInfo SwitchToFFWInfo
            {
                get
                {
                    return _switchtoffwInfo;
                }
            }
        }

        /// <summary>
        /// The SystemExitAppFolder folder.
        /// </summary>
        [RepositoryFolder("e1a214e0-aa51-496b-bc20-190b7f0a7139")]
        public partial class SystemExitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inspectedtextInfo;

            /// <summary>
            /// Creates a new SystemExit  folder.
            /// </summary>
            public SystemExitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SystemExit", "/form[@title='System Exit']", parentFolder, 30000, null, true, "e1a214e0-aa51-496b-bc20-190b7f0a7139", "")
            {
                _inspectedtextInfo = new RepoItemInfo(this, "InspectedText", "text[@controlid='1571']", 30000, null, "b79a0d8b-2d56-43d3-8c37-235fe4dbc09f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e1a214e0-aa51-496b-bc20-190b7f0a7139")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e1a214e0-aa51-496b-bc20-190b7f0a7139")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InspectedText item.
            /// </summary>
            [RepositoryItem("b79a0d8b-2d56-43d3-8c37-235fe4dbc09f")]
            public virtual Ranorex.Text InspectedText
            {
                get
                {
                    return _inspectedtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The InspectedText item info.
            /// </summary>
            [RepositoryItemInfo("b79a0d8b-2d56-43d3-8c37-235fe4dbc09f")]
            public virtual RepoItemInfo InspectedTextInfo
            {
                get
                {
                    return _inspectedtextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}