///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ExitPromptText
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            //bool bBigMode = true;

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.MeasureText' at Center.", repo.SnapXUntitled.MeasureTextInfo, new RecordItemIndex(0));
            //repo.SnapXUntitled.MeasureText.MoveTo();
            //Delay.Milliseconds(200);
            //bBigMode = repo.SnapXUntitled.MeasureText.Visible;

            //if (bBigMode)
            //{
            //    Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.TitleBar' at 700;12.", repo.SnapXUntitled.TitleBarInfo, new RecordItemIndex(2));
            //    repo.SnapXUntitled.TitleBar.Click("700;12");
            //    Delay.Milliseconds(200);
            //}

            //else
            //{
            //    Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.SwitchToSensor' at Center.", repo.SnapXUntitled.SwitchToSensorInfo, new RecordItemIndex(1));
            //    repo.SnapXUntitled.SwitchToSensor.Click();
            //    Delay.Milliseconds(200);
            //}

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.TitleBar' at 700;12.", repo.SnapXUntitled.TitleBarInfo, new RecordItemIndex(2));
            //repo.SnapXUntitled.TitleBar.Click("700;12");
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(3));
            //Keyboard.Press("{LMenu}");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f'.", new RecordItemIndex(4));
            //Keyboard.Press("f");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'x'.", new RecordItemIndex(5));
            //Keyboard.Press("x");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit' at 188;45.", repo.SystemExit.SelfInfo, new RecordItemIndex(6));
            //repo.SystemExit.Self.Click("188;45");
            //Delay.Milliseconds(200);

            //string strTitleText = repo.SystemExit.Self.Title;
            //string strHardcodedTitleText = "System Exit";
            //UtilityRun.TitleText(strTitleText, strHardcodedTitleText);
            //Delay.Milliseconds(200);


            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit.InspectedText' at 93;6.", repo.SystemExit.InspectedTextInfo, new RecordItemIndex(7));
            //repo.SystemExit.InspectedText.Click("93;6");
            //Delay.Milliseconds(200);

            //string strActualMessage = repo.SystemExit.InspectedText.TextValue;
            //string strHardcodetMessage = "This will end your Snap-X session.";
            //UtilityRun.TitleText(strActualMessage, strHardcodetMessage);
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(8));
            //Keyboard.Press("c");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.TitleBar' at 1521;14.", repo.SnapXUntitled.TitleBarInfo, new RecordItemIndex(9));
            //repo.SnapXUntitled.TitleBar.Click("1521;14");
            //Delay.Milliseconds(200);


            ////// continue from here//////////////

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit' at 188;45.", repo.SystemExit.SelfInfo, new RecordItemIndex(10));
            //repo.SystemExit.Self.Click("188;45");
            //Delay.Milliseconds(200);

            //string strActualText = repo.SystemExit.Self.Title;
            //string strHardcodedActualText = "System Exit";
            //UtilityRun.TitleText(strActualText, strHardcodedActualText);
            //Delay.Milliseconds(200);


            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit.InspectedText' at 93;6.", repo.SystemExit.InspectedTextInfo, new RecordItemIndex(11));
            //repo.SystemExit.InspectedText.Click("93;6");
            //Delay.Milliseconds(200);

            //string strActualPromptText = repo.SystemExit.InspectedText.TextValue;
            //string strHardcodedPromptText = "This will end your Snap-X session.";
            //UtilityRun.TitleText(strActualPromptText, strHardcodedPromptText);
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(12));
            //Keyboard.Press("c");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.SwitchToFFW' at Center.", repo.SnapXUntitled.SwitchToFFWInfo, new RecordItemIndex(13));
            //repo.SnapXUntitled.SwitchToFFW.Click();
            //Delay.Milliseconds(200);

            ////Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.TitleBar' at Center.", repo.SnapXUntitled.TitleBarInfo, new RecordItemIndex(14));
            ////repo.SnapXUntitled.TitleBar.Click();
            ////Delay.Milliseconds(200);

            ////Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LMenu}'.", new RecordItemIndex(15));
            ////Keyboard.Press("{LMenu}");
            ////Delay.Milliseconds(0);

            ////Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'f'.", new RecordItemIndex(16));
            ////Keyboard.Press("f");
            ////Delay.Milliseconds(0);

            ////Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'x'.", new RecordItemIndex(17));
            ////Keyboard.Press("x");
            ////Delay.Milliseconds(0);

            ////Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit' at 188;45.", repo.SystemExit.SelfInfo, new RecordItemIndex(18));
            ////repo.SystemExit.Self.Click("188;45");
            ////Delay.Milliseconds(200);

            ////Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit.InspectedText' at 93;6.", repo.SystemExit.InspectedTextInfo, new RecordItemIndex(19));
            ////repo.SystemExit.InspectedText.Click("93;6");
            ////Delay.Milliseconds(200);

            ////Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(20));
            ////Keyboard.Press("c");
            ////Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.TitleBar' at 1521;14.", repo.SnapXUntitled.TitleBarInfo, new RecordItemIndex(21));
            //repo.SnapXUntitled.TitleBar.Click("1521;14");
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit' at 188;45.", repo.SystemExit.SelfInfo, new RecordItemIndex(22));
            //repo.SystemExit.Self.Click("188;45");
            //Delay.Milliseconds(200);

            //string strFFWActualValue = repo.SystemExit.Self.Title;
            //string strHardcodedFFWActualValue = "System Exit";
            //UtilityRun.TitleText(strFFWActualValue, strHardcodedFFWActualValue);
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SystemExit.InspectedText' at 93;6.", repo.SystemExit.InspectedTextInfo, new RecordItemIndex(23));
            //repo.SystemExit.InspectedText.Click("93;6");
            //Delay.Milliseconds(200);

            //string strFFWActualPromptText = repo.SystemExit.InspectedText.TextValue;
            //string strFFWhardcodedPromptText = "This will end your Snap-X session.";
            //UtilityRun.TitleText(strFFWActualPromptText, strFFWhardcodedPromptText);
            //Delay.Milliseconds(200);

            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'c'.", new RecordItemIndex(24));
            //Keyboard.Press("c");
            //Delay.Milliseconds(0);

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SnapXUntitled.SwitchToSensor' at Center.", repo.SnapXUntitled.SwitchToSensorInfo, new RecordItemIndex(25));
            //repo.SnapXUntitled.SwitchToSensor.Click();
            //Delay.Milliseconds(200);
        }

    }
}
